export const fonts = [
  // System / Classic
  'Arial',
  'Helvetica',
  'Times New Roman',
  'Courier New',
  'Verdana',
  'Georgia',
  'Palatino',
  'Garamond',
  'Bookman',
  'Comic Sans MS',
  'Trebuchet MS',
  'Arial Black',
  'Impact',
  'Lucida Sans Unicode',
  'Tahoma',
  'Courier',
  'Lucida Console',

  // Modern Sans-Serif
  'Inter',
  'Inter Tight',
  'Roboto',
  'Open Sans',
  'Lato',
  'Montserrat',
  'Poppins',
  'Nunito',
  'Nunito Sans',
  'Raleway',
  'Oswald',
  'Roboto Condensed',
  'Work Sans',
  'Merriweather Sans',
  'Noto Sans',
  'Fira Sans',
  'Titillium Web',
  'PT Sans',
  'IBM Plex Sans',
  'IBM Plex Mono',
  'Josefin Sans',
  'Quicksand',
  'Karla',
  'Rubik',
  'Overpass',
  'Cabin',
  'Oxygen',
  'Hind',
  'Mukta',
  'Cairo',
  'Rajdhani',
  'Kanit',
  'Prompt',
  'Barlow',
  'Barlow Condensed',
  'Maven Pro',
  'Signika',
  'Play',
  'Cuprum',
  'Archivo',
  'Archivo Black',
  'Archivo Narrow',
  'Cabin Condensed',

  // New Modern Favorites (Google Fonts 2020+)
  'DM Sans',
  'DM Serif Display',
  'DM Mono',
  'Plus Jakarta Sans',
  'Space Grotesk',
  'Sora',
  'Manrope',
  'Outfit',
  'Lexend',
  'Lexend Deca',
  'Figtree',
  'Be Vietnam Pro',
  'Albert Sans',
  'Onest',
  'Urbanist',
  'Chivo',
  'Epilogue',
  'Familjen Grotesk',
  'Hanken Grotesk',
  'Bricolage Grotesque',
  'Instrument Sans',
  'Jost',

  // Serif / Classic Editorial
  'Merriweather',
  'Playfair Display',
  'Playfair Display SC',
  'Roboto Slab',
  'Source Sans Pro',
  'Lora',
  'Arvo',
  'Cormorant Garamond',
  'Bitter',
  'PT Serif',
  'Noto Serif',
  'Libre Baskerville',
  'Crimson Text',
  'EB Garamond',
  'Philosopher',
  'Spectral',
  'Libre Franklin',
  'Cinzel',
  'Cardo',
  'Zilla Slab',

  // Monospace / Code
  'Roboto Mono',
  'Source Code Pro',
  'Inconsolata',
  'Fira Mono',
  'Ubuntu Mono',
  'Space Mono',
  'Courier Prime',
  'JetBrains Mono',

  // Display / Decorative
  'Bebas Neue',
  'Anton',
  'Abril Fatface',
  'Pacifico',
  'Lobster',
  'Tangerine',
  'Comfortaa',
  'Poiret One',
  'Varela Round',
  'Baloo 2',
  'Exo',
  'Exo 2',
  'Dosis',
  'Yanone Kaffeesatz',
  'Montserrat Alternates',
  'Josefin Slab',
  'Permanent Marker',
  'Dancing Script',
  'Sacramento',
  'Great Vibes',
  'Satisfy',
  'Caveat',
  'Kalam',
  'Patrick Hand',
  'Ubuntu',
  'Ubuntu Condensed',
  'Fira Sans Condensed',
  'Abel',
  'PT Sans Narrow',
  'Muli',
  'Droid Sans',
  'Yantramanav',
  'Avenir',
].sort();

export const DEFAULT_FONT = 'Montserrat';
