export const fonts = [
    'Arial',
    'Helvetica',
    'Times New Roman',
    'Courier New',
    'Verdana',
    'Georgia',
    'Palatino',
    'Garamond',
    'Bookman',
    'Comic Sans MS',
    'Trebuchet MS',
    'Arial Black',
    'Impact',
    'Lucida Sans Unicode',
    'Tahoma',
    'Courier',
    'Lucida Console',
    'Roboto',
    'Open Sans',
    'Lato',
    'Montserrat',
    'Roboto Slab',
    'Source Sans Pro',
    'Raleway',
    'Oswald',
    'Roboto Condensed',
    'Nunito',
    'Merriweather',
    'Playfair Display',
    'Roboto Mono',
    'Ubuntu',
    'Avenir',
    'Cabin',
    'Work Sans',
    'Merriweather Sans',
    'Noto Sans',
    'Fira Sans',
    'Titillium Web',
    'Muli',
    'PT Sans',
    'IBM Plex Sans',
    'Josefin Sans',
    'Montserrat Alternates',
    'Quicksand',
    'Droid Sans',
    'Karla',
    'Bebas Neue',
    'Lora',
    'Exo',
    'Exo 2',
    'Dosis',
    'Rubik',
    'Pacifico',
    'Varela Round',
    'Arvo',
    'Cormorant Garamond',
    'Archivo',
    'Cabin Condensed',
    'Oxygen',
    'Yantramanav',
    'Abel',
    'Bitter',
    'PT Sans Narrow',
    'Noto Serif',
    'Anton',
    'Overpass',
    'Nunito Sans',
    'Rajdhani',
    'Inconsolata',
    'Source Code Pro',
    'Tangerine',
    'Abril Fatface',
    'Ubuntu Condensed',
    'Fira Sans Condensed',
    'Maven Pro',
    'PT Serif',
    'Crimson Text',
    'Signika',
    'Cairo',
    'Play',
    'EB Garamond',
    'Hind',
    'Mukta',
    'Philosopher',
    'Archivo Black',
    'Comfortaa',
    'Poiret One',
    'Barlow',
    'Cuprum',
    'Archivo Narrow',
    'Playfair Display SC',
    'Yanone Kaffeesatz',
    'Libre Baskerville',
    'Barlow Condensed',
    'Baloo',
    'Lobster',
    'Kanit',
    'Prompt',
    'Poppins'
  ];
  
  
  export const DEFAULT_FONT = 'Montserrat';